version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env   
    command: [ "/bin/sh", "-c", "composer i --no-progress && php artisan migrate && php-fpm" ]
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - test_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    ports:
      - "3306:3306"

  nginx:
    image: nginx:latest
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
    depends_on:
      - php

volumes:
  test_db:
